name: Doxygen Documentation

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the 'main' branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen  # Install Doxygen directly via apt

        

      - name: Generate Documentation
        run: doxygen Doxyfile  # Run Doxygen with your 'Doxyfile'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploys generated docs to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          publish_dir: ./docs/html  # Directory where Doxygen generates docs (ensure this matches your config)

