name: Python Tests

# Trigger the workflow on pushes and pull requests
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the job
jobs:
  test:
    runs-on: ubuntu-latest

    # Define the steps
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: |
        pytest --cov=your_project_directory --cov-report=term-missing
